# Site settings
title: Le journal de YoungFrog
email: nrichard@members.fsf.org
description: Les errements de ma pensée, parfois nus, parfois enrobés. Mes écrits n'engagent que ceux qui y croient, mais pas trop.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: youngfrog
github_username:  youngfrog

# Build settings
markdown: kramdown
future: false